### ISSUE TITLE
Confirm API for SSH connection from Java

### ISSUE THREAD

**Issue by a2l007** [airavata-courses/TeamZenith#1]
The Jsch library from JCraft is a good choice for serving our purpose of SSH connection and remote command execution. It also supports private key authentication, which would enable password-less authentication for the purpose of connecting to the Karst domain.
We can discuss alternatives if available, but it looks like Jsch should serve the purpose.

**Comment by anujbhan** [comment]
jsch works just fine

**Comment by arpiagariu** [comment]
Important resources
