### ISSUE TITLE
Config File Suggestion

### ISSUE THREAD

**Issue by sanketmhaiskar** [airavata-courses/TeamZenith#11]
Not an issue for now but you could make use of the config file for storing the properties for a particular application instead of taking it from the Console.

**Comment by arpiagariu** [comment]
Thanks @sanketmhaiskar  It is a design choice and we preferred taking these parameters from console with a view of not changing the config file again and again.

If you are satisfied with the explanation please close the issue.

**Comment by arpiagariu** [comment]
Valid explanation provided. Hence closing this issue
