### ISSUE TITLE
Job Status Monitoring

### ISSUE THREAD

**Issue by sanketmhaiskar** [airavata-courses/TeamZenith#14]
Allowing the user to view job status from the application itself can also be implemented . Instead of polling , may be on-demand job status viewing option.

**Comment by anujbhan** [comment]
It is our design choice, for the above suggestion, we would have to open multiple ssh sessions or keep the existing ssh session open, which will result in waste of bandwidth.

**Comment by arpiagariu** [comment]
We have implemented this.  Hence closing the defect
