### ISSUE TITLE
Avoid Direct String Concatenation

### ISSUE THREAD

**Issue by abhijitkaranjkar89** [airavata-courses/TeamZenith#18]
Avoid direct string concatenation. It is a heavy operation. Instead use StringBuffer or StringBuilder.
These things may not matter at small level project but they do when you scale your project up and you have limited heap size.

Avoid:
"usage: java KeyGen rsa output_keyfile comment\n"+
"       java KeyGen dsa output_keyfile comment\n"+
"       java KeyGen ecdsa-sha2-256 output_keyfile comment\n"+
"       java KeyGen ecdsa-sha2-384 output_keyfile comment\n"+
"       java KeyGen ecdsa-sha2-521 output_keyfile comment"

KeyGen.java

**Comment by a2l007** [comment]
This has been taken care of in the 2nd milestone. Thanks for pointing out.
