### ISSUE TITLE
GROMACS submission for Milestone 3

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamZenith#28]
To complete milestone 3, you need to support GROMACS submission.  UI looks great.

**Comment by a2l007** [comment]
Marlon,
In addition to adding the required modules, we tried the exact steps as mentioned in: https://github.com/SciGaP/XSEDE-Job-Scripts/blob/master/Trestles/GROMACS/README
but, the commands being used for gromacs: pdb2gmx and grompp are unavailable in Karst. As a result the job fails. Are you aware of any other configuration that needs to be done before Gromacs can be run?

**Comment by marpierc** [comment]
You need to load the modules: module load gromacs. See the list in the KB article on gromacs: https://kb.iu.edu/d/besc

**Comment by a2l007** [comment]
Hello Marlon,
As described in my earlier update, I have already loaded the required modules, that are: openmpi/intel/1.6.3 and gromacs/intel/4.6.5

**Comment by marpierc** [comment]
OK I see a difference now: if I load module load openmpi/intel/1.6.3 and  module load gromacs/intel/4.6.5, then the commands are not there.  

But if I just use "module load gromacs", I see the following output:
[marpierc@h3 ~]$ module load gromacs
GROMACS molecular dynamics package version 4.6.5 loaded.
[marpierc@h3 ~]$ 
/N/soft/rhel6/gromacs/intel/serial/4.6.5/bin/grompp
[marpierc@h3 ~]$ which pdb2gmx
/N/soft/rhel6/gromacs/intel/serial/4.6.5/bin/pdb2gmx

**Comment by marpierc** [comment]
This is the serial version of GROMACS but given the other issues, it's fine if this works.

**Comment by a2l007** [comment]
We got GROMACS working and have pushed the required changes into Milestone-3 branch. Please review.

**Comment by a2l007** [comment]
Closing the issue as Milestone3 has been graded.
