### ISSUE TITLE
Amazon Accounts 

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamZenith#31]
Please let me know who in your group wants access to the TeamZenith group I created in Amazon. This should give you full access to the Amazon Cloud API so that you can manage your own VMs.  Minimally one person per team needs to be the group VM administrator, but I will give access to everyone on the team who asks.

**Comment by anujbhan** [comment]
Yes Marlon, if it is feasible can you give all of us the admin accounts/ privileges. I will now send a mail with my private key. Will also notify other to send too.
