### ISSUE TITLE
GROMACS submission on BR2 for Milestone 4 isn't working

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamZenith#47]
I get the following error. Looks like you haven't gotten the modules loaded properly.

marpierc@login1:~/workspace> more testbr2.err 
gromacs/gnu/single/5.0.4(34):ERROR:151: Module 'gromacs/gnu/single/5.0.4' depends on one of the module(s) 'PrgEnv-gnu/5.2.82'
gromacs/gnu/single/5.0.4(34):ERROR:102: Tcl command execution failed: prereq PrgEnv-gnu

/var/spool/torque/mom_priv/jobs/1288733.SC: line 12: pdb2gmx: command not found
/var/spool/torque/mom_priv/jobs/1288733.SC: line 13: grompp: command not found
/var/spool/torque/mom_priv/jobs/1288733.SC: line 14: mdrun: command not found

**Comment by a2l007** [comment]
Hello Marlon,
Could you please grade Milestone 4? We have fixed the gromacs bug on BR2.
