### ISSUE TITLE
Milestone 6 Also Should Use CI/CD

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamZenith#51]
Your Milestone 6 instructions are for a local installation. As specified in the assignment instructions, you should build on Milestone 5's CI/CD. You should use Travis-CI.

**Comment by anujbhan** [comment]
Milestone 6 is configured for Continuous deployment.

There are two branches for Milestone 6, Milestone-6 and Mikestone-6 UI.
Both branches are setup to deploy on two separate instances of Amazon EC2

**Comment by anujbhan** [comment]
I forgot to include the build status flag on respective Readme files, If you permit, ill include the flag which makes to easier to check the deployment status

**Comment by marpierc** [comment]
OK, what are the URLs for the VMs? If I make a harmless commit on each branch, will this fire off Travis-CI?  Also, is there a way to verify that the VM was updated?

Thanks,

Marlon

**Comment by marpierc** [comment]
Yes, go ahead.

**Comment by anujbhan** [comment]
https://travis-ci.org/airavata-courses/TeamZenith --> travis status check

**Comment by anujbhan** [comment]
I have updated both branch Readme files with testing urls. Please reply back if any clarifications are needed
