### ISSUE TITLE
URL for Milestone 6?

### ISSUE THREAD

**Issue by marpierc** [airavata-courses/TeamZenith#52]
Is the gateway UI URL https://52.38.43.52:8443/ for Milestone 6.

**Comment by anujbhan** [comment]
Yes Marlon, it is for milestone 6 UI module

**Comment by marpierc** [comment]
I was able to login but my job didn’t work. I’m getting "You failed to upload pdb1y6l.ent => pdb1y6l.ent (Permission denied)"

**Comment by anujbhan** [comment]
I'll check and reply ASAP
